// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pb/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenrePeriodDetailsRequest_Operator int32

const (
	GenrePeriodDetailsRequest_OP_LT GenrePeriodDetailsRequest_Operator = 0
	GenrePeriodDetailsRequest_OP_EQ GenrePeriodDetailsRequest_Operator = 1
	GenrePeriodDetailsRequest_OP_GT GenrePeriodDetailsRequest_Operator = 2
)

// Enum value maps for GenrePeriodDetailsRequest_Operator.
var (
	GenrePeriodDetailsRequest_Operator_name = map[int32]string{
		0: "OP_LT",
		1: "OP_EQ",
		2: "OP_GT",
	}
	GenrePeriodDetailsRequest_Operator_value = map[string]int32{
		"OP_LT": 0,
		"OP_EQ": 1,
		"OP_GT": 2,
	}
)

func (x GenrePeriodDetailsRequest_Operator) Enum() *GenrePeriodDetailsRequest_Operator {
	p := new(GenrePeriodDetailsRequest_Operator)
	*p = x
	return p
}

func (x GenrePeriodDetailsRequest_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenrePeriodDetailsRequest_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_server_proto_enumTypes[0].Descriptor()
}

func (GenrePeriodDetailsRequest_Operator) Type() protoreflect.EnumType {
	return &file_pb_server_proto_enumTypes[0]
}

func (x GenrePeriodDetailsRequest_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenrePeriodDetailsRequest_Operator.Descriptor instead.
func (GenrePeriodDetailsRequest_Operator) EnumDescriptor() ([]byte, []int) {
	return file_pb_server_proto_rawDescGZIP(), []int{0, 0}
}

type GenrePeriodDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreId              int64                              `protobuf:"varint,1,opt,name=genreId,proto3" json:"genreId,omitempty"`
	StartDate            *timestamppb.Timestamp             `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              *timestamppb.Timestamp             `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Revenue              int64                              `protobuf:"varint,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	RevenueCheckOperator GenrePeriodDetailsRequest_Operator `protobuf:"varint,5,opt,name=revenueCheckOperator,proto3,enum=movie.GenrePeriodDetailsRequest_Operator" json:"revenueCheckOperator,omitempty"`
}

func (x *GenrePeriodDetailsRequest) Reset() {
	*x = GenrePeriodDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenrePeriodDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenrePeriodDetailsRequest) ProtoMessage() {}

func (x *GenrePeriodDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenrePeriodDetailsRequest.ProtoReflect.Descriptor instead.
func (*GenrePeriodDetailsRequest) Descriptor() ([]byte, []int) {
	return file_pb_server_proto_rawDescGZIP(), []int{0}
}

func (x *GenrePeriodDetailsRequest) GetGenreId() int64 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *GenrePeriodDetailsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GenrePeriodDetailsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GenrePeriodDetailsRequest) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *GenrePeriodDetailsRequest) GetRevenueCheckOperator() GenrePeriodDetailsRequest_Operator {
	if x != nil {
		return x.RevenueCheckOperator
	}
	return GenrePeriodDetailsRequest_OP_LT
}

type GenrePeriodDetailsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenreId int64       `protobuf:"varint,1,opt,name=genreId,proto3" json:"genreId,omitempty"`
	Name    string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pct     float32     `protobuf:"fixed32,3,opt,name=pct,proto3" json:"pct,omitempty"`
	Movies  []*MovieMsg `protobuf:"bytes,4,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *GenrePeriodDetailsReply) Reset() {
	*x = GenrePeriodDetailsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenrePeriodDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenrePeriodDetailsReply) ProtoMessage() {}

func (x *GenrePeriodDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenrePeriodDetailsReply.ProtoReflect.Descriptor instead.
func (*GenrePeriodDetailsReply) Descriptor() ([]byte, []int) {
	return file_pb_server_proto_rawDescGZIP(), []int{1}
}

func (x *GenrePeriodDetailsReply) GetGenreId() int64 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *GenrePeriodDetailsReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenrePeriodDetailsReply) GetPct() float32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *GenrePeriodDetailsReply) GetMovies() []*MovieMsg {
	if x != nil {
		return x.Movies
	}
	return nil
}

type MovieMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseDate string `protobuf:"bytes,3,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	Revenue     int64  `protobuf:"varint,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
}

func (x *MovieMsg) Reset() {
	*x = MovieMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieMsg) ProtoMessage() {}

func (x *MovieMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieMsg.ProtoReflect.Descriptor instead.
func (*MovieMsg) Descriptor() ([]byte, []int) {
	return file_pb_server_proto_rawDescGZIP(), []int{2}
}

func (x *MovieMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieMsg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieMsg) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *MovieMsg) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

var File_pb_server_proto protoreflect.FileDescriptor

var file_pb_server_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x02, 0x0a, 0x19, 0x47, 0x65,
	0x6e, 0x72, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x5d, 0x0a, 0x14, 0x72,
	0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x14, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x08, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x50, 0x5f, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x50, 0x5f, 0x45, 0x51, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x4f, 0x50, 0x5f, 0x47, 0x54, 0x10, 0x02, 0x22, 0x82, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x70, 0x63, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x22, 0x6c, 0x0a, 0x08,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x32, 0x66, 0x0a, 0x05, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x12, 0x5d, 0x0a, 0x17, 0x46, 0x65, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x20,
	0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x66, 0x66, 0x61, 0x6e, 0x73, 0x68, 0x61, 0x68, 0x69, 0x64, 0x2f, 0x63, 0x6f, 0x6e,
	0x76, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2d, 0x66, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_server_proto_rawDescOnce sync.Once
	file_pb_server_proto_rawDescData = file_pb_server_proto_rawDesc
)

func file_pb_server_proto_rawDescGZIP() []byte {
	file_pb_server_proto_rawDescOnce.Do(func() {
		file_pb_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_server_proto_rawDescData)
	})
	return file_pb_server_proto_rawDescData
}

var file_pb_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_server_proto_goTypes = []interface{}{
	(GenrePeriodDetailsRequest_Operator)(0), // 0: movie.GenrePeriodDetailsRequest.Operator
	(*GenrePeriodDetailsRequest)(nil),       // 1: movie.GenrePeriodDetailsRequest
	(*GenrePeriodDetailsReply)(nil),         // 2: movie.GenrePeriodDetailsReply
	(*MovieMsg)(nil),                        // 3: movie.MovieMsg
	(*timestamppb.Timestamp)(nil),           // 4: google.protobuf.Timestamp
}
var file_pb_server_proto_depIdxs = []int32{
	4, // 0: movie.GenrePeriodDetailsRequest.startDate:type_name -> google.protobuf.Timestamp
	4, // 1: movie.GenrePeriodDetailsRequest.endDate:type_name -> google.protobuf.Timestamp
	0, // 2: movie.GenrePeriodDetailsRequest.revenueCheckOperator:type_name -> movie.GenrePeriodDetailsRequest.Operator
	3, // 3: movie.GenrePeriodDetailsReply.movies:type_name -> movie.MovieMsg
	1, // 4: movie.Movie.FetchGenrePeriodDetails:input_type -> movie.GenrePeriodDetailsRequest
	2, // 5: movie.Movie.FetchGenrePeriodDetails:output_type -> movie.GenrePeriodDetailsReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_server_proto_init() }
func file_pb_server_proto_init() {
	if File_pb_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenrePeriodDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenrePeriodDetailsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_server_proto_goTypes,
		DependencyIndexes: file_pb_server_proto_depIdxs,
		EnumInfos:         file_pb_server_proto_enumTypes,
		MessageInfos:      file_pb_server_proto_msgTypes,
	}.Build()
	File_pb_server_proto = out.File
	file_pb_server_proto_rawDesc = nil
	file_pb_server_proto_goTypes = nil
	file_pb_server_proto_depIdxs = nil
}
