// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	tmdb "github.com/cyruzin/golang-tmdb"
	mock "github.com/stretchr/testify/mock"
)

// MovieCache is an autogenerated mock type for the MovieCache type
type MovieCache struct {
	mock.Mock
}

// GetMovieDetails provides a mock function with given fields: id
func (_m *MovieCache) GetMovieDetails(id int64) (*tmdb.MovieDetails, error) {
	ret := _m.Called(id)

	var r0 *tmdb.MovieDetails
	if rf, ok := ret.Get(0).(func(int64) *tmdb.MovieDetails); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdb.MovieDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveMovieDetails provides a mock function with given fields: movie
func (_m *MovieCache) SaveMovieDetails(movie *tmdb.MovieDetails) error {
	ret := _m.Called(movie)

	var r0 error
	if rf, ok := ret.Get(0).(func(*tmdb.MovieDetails) error); ok {
		r0 = rf(movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
